### PR TITLE
play 2.4 support

### PR DESCRIPTION
**Pull request by joscha**
see #38 and #39.

### CODE REVIEW

**Comment by joscha** [comment]
cc @vmouta @mkurz

**Comment by joscha** [comment]
The snapshot should go live on sonatype in a bit - as soon as the travis run on master is done.

**Comment by joscha** [comment]
`0.7.0-SNAPSHOT` is live on [sonatype](https://oss.sonatype.org/content/repositories/snapshots/com/feth/play-easymail_2.11/0.7.0-SNAPSHOT/).

**Comment by mkurz** [comment]
@joscha :+1: Thanks!
Sorry I couldn't finish play-authenticate yesterday anymore.... Working on it right now :smile:

**Pull request merged**
