### PR TITLE
migrate to play! 2.5

### PR DESCRIPTION
**Pull request by oexza**
@joscha  @mkurz  please review amd merge thanks.

### CODE REVIEW

**Comment by joscha** [comment]
Thanks @oexza - looks good, however we need to fix the tests before merging:

```
[error] /home/travis/build/joscha/play-easymail/samples/play-easymail-usage/app/controllers/Application.java:4:  error: cannot find symbol
[error] import com.feth.play.module.mail.Mailer.Mail;
[error]                                        ^
[error] (compile:compileIncremental) javac returned nonzero exit code
[error] Total time: 20 s, completed Mar 19, 2016 3:21:30 PM
```

**Comment by oexza** [comment]
ahh! that was an oversight, i shall see to it by the end of today.

**Comment by oexza** [comment]
@joscha done!

**Comment by oexza** [comment]
ping! @joscha    :smiley:

**Comment by joscha** [comment]
Thanks! `0.8.0-SNAPSHOT` was pushed to sonatype - let me know if that version works for you!

**Pull request merged**
