### PR TITLE
Master

### PR DESCRIPTION
**Pull request by vmouta**
My suggestion for update. Notice “public class Mail extends Email“ from play-mail library i believe it to be a good idea specially for the future.

### CODE REVIEW

**Comment by mkurz** [comment]
@vmouta You do not need to close and create a new Pull Request every time you make a change. Just push the changes of your branch to github and the Pull Request will pick up the new commits and changes.

**Comment by mkurz** [comment]
@vmouta Can you please rebase you branch against the `master` branch? Thanks!

**Comment by mkurz** [comment]
I will have a look tomorrow and maybe add some enhancements.

**Comment by joscha** [comment]
closed in favor of #39.

**Pull request closed without merging**
