### PR TITLE
Add support for Play 2.4

### PR DESCRIPTION
**Pull request by mkurz**
I squashed the commits from @vmouta from #38 into one nice, single commit.
Then I cleaned up the code a bit.

I also support the strategy vmouta is taking by extending Play's `Email` class, which saves us a lot of redundant code (e.g. we do not need the `Attachment` class anymore) because basically all functionality is implemented by the play-mailer module already.

One more thing: This PR does not use dependency injection yet (The `MailerPlugin` is deprecated) . It's ok for now, but for Play 3.0 this has to be addressed, as Plugins will be removed in favor of Modules written with DI.

@joscha Could you please review this PR and if you are fine with it merge and release a snapshot so people can test?

### CODE REVIEW

**Comment by mkurz** [comment]
CI fails because it uses OpenJDK6 but Play 2.4 requires Java 8 now. Java 6 and 7 are not supported anymore...

**Comment by joscha** [comment]
Thanks @vmouta and @mkurz!
How would you two feel about becoming collaborators on this project and play-authenticate?

**Comment by mkurz** [comment]
@joscha Yes I think I can do that. I just don't know how much time I can spend, depending on the projects I am working on. But I am sure I can at least review PR's and answer issues. :smile:

**Comment by mkurz** [comment]
Also I am working on Play 2.4 support for play-authenticate right now. I am almost done already. I have to pick up a friend now, but probably within the next 2 - 3 hours I will provide the PR :beers:

**Comment by vmouta** [comment]
As you guys notice I’m still a noobie… if someone keep an eye I can keep trying

**Comment by joscha** [comment]
Awesome, I added you! @vmouta we all started somewhere - and we have git :)

**Pull request merged**
