### PR TITLE
Migrate to play 2.6

### PR DESCRIPTION
**Pull request by KadekM**
Would this be sufficient?
For #53.

### CODE REVIEW

**Comment by KadekM** [comment]
@joscha fixed

**Comment by joscha** [comment]
release as `0.9.0` on Sonatype, had to add a few more fixes to make it work. Should appear soon.

**Comment by KadekM** [comment]
Thanks.

**Comment by joscha** [comment]
`0.9.3` is cross compiled for Scala 2.11 and 2.12

**Pull request merged**
